---
- name: Backup running configuration from IOS-XE device
  hosts: cisco_csr1000v
  gather_facts: false
  connection: network_cli
  
  tasks:
  - name: Backup running configuration
    cisco.ios.ios_config:
      backup: true
      backup_options:
        filename: "startup-config.cfg"
        dir_path: clab-uninet-lab-v1/{{ inventory_hostname_short }}/config
    register: backup_result
