---

- name: Show IOS-XR release
  hosts: xrd
  gather_facts: false
  
  tasks:
  - name: Show ver
    cisco.iosxr.iosxr_command:
      commands: 
      - 'show ver'
    register: output

  - name: print captured output
    ansible.builtin.debug:
      msg: "{{ output['stdout_lines'][0][8] }}"


- name: Show IOS-XE release
  hosts: cisco_csr1000v
  gather_facts: false
  
  tasks:
  - name: Show ver
    cisco.ios.ios_command:
      commands: 
      - 'show ver'
    register: output

  - name: print captured output
    ansible.builtin.debug:
      msg: "{{ output['stdout_lines'][0][1] }}"


- name: Show Junos release
  hosts: crpd
  gather_facts: false

  tasks:
  - name: Show ver
    junipernetworks.junos.junos_command:
      commands: 
      - 'show ver'
    register: output

  - name: print captured output
    ansible.builtin.debug:
       msg: "{{ output['stdout_lines'][0][2] }}"
